name: Test Success final

on:
  push:
    branches:
      - main
jobs:
  success-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo success
        run: echo "Success"
      - name: Notify Scoutflo AutoCD
        run: |
          curl -X POST https://api.app-server-pp.scoutflo.com/v1/autocd/trigger \
            -H "Authorization: Bearer ${{ secrets.SCOUTFLO_WEBHOOK_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Origin: https://app-pp.scoutflo.com" \
            -d '{
              "provider": "github",
              "repo": "${{ github.repository }}",
              "branch": "${{ github.ref_name }}",
              "commit": "${{ github.sha }}",
              "images": [
                {
                  "registry_provider": "AWS_ECR",
                  "image_repo": "welcome-scoutflo",
                  "image_tag": "69.0.0",
                  "service_labels": ["sl_pYO_R0iVvUjRtC8kuyvBA"]
                }
              ]
            }'
