name: Test Success

on:
  workflow_dispatch:

jobs:
  success-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo success
        run: echo "Success âœ…"

      - name: Notify Scoutflo AutoCD
        run: |
          curl -X POST https://api.app-server-pp.scoutflo.com/v1/autocd/trigger \
            -H "Authorization: Bearer ${{ secrets.SCOUTFLO_WEBHOOK_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "provider": "github",
              "service_name": "autocd-test-1",
              "cloud_connection_id": "cloud-credentials-4a9ecee0-f9e0-4331-bab6-ed5ba76d2c5a",
              "registry": "AWS_ECR",
              "image_repo": "welcome-scoutflo",
              "image_tag": "${{ github.sha }}",
              "image_digest": "sha256:REPLACE_ME",
              "repo": "${{ github.repository }}",
              "branch": "${{ github.ref_name }}",
              "commit": "${{ github.sha }}"
            }'
